### ISSUE TITLE
Error starting this repo with npm start command

### ISSUE THREAD

**Issue by DVGY** [silevis/reactgrid#171]
```
PS G:\gitLocal\reactgrid> npm start

> @silevis/reactgrid@4.0.4 start
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (G:\gitLocal\reactgrid\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (G:\gitLocal\reactgrid\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (G:\gitLocal\reactgrid\node_modules\webpack\lib\NormalModule.js:471:10)
    at G:\gitLocal\reactgrid\node_modules\webpack\lib\NormalModule.js:503:5
    at G:\gitLocal\reactgrid\node_modules\webpack\lib\NormalModule.js:358:12
    at G:\gitLocal\reactgrid\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (G:\gitLocal\reactgrid\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (G:\gitLocal\reactgrid\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
G:\gitLocal\reactgrid\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (G:\gitLocal\reactgrid\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (G:\gitLocal\reactgrid\node_modules\webpack\lib\NormalModule.js:417:16)
    at G:\gitLocal\reactgrid\node_modules\webpack\lib\NormalModule.js:452:10
    at G:\gitLocal\reactgrid\node_modules\webpack\lib\NormalModule.js:323:13
    at G:\gitLocal\reactgrid\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\gitLocal\reactgrid\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\gitLocal\reactgrid\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\gitLocal\reactgrid\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
PS G:\gitLocal\reactgrid>
```

 - Device:  Windows 10 Desktop
 - Node version: 18.16.0

**Comment by alonshmiel** [comment]
Hi @DVGY , I guess you upgraded your node to 18.

You can add this and it works:
export NODE_OPTIONS=--openssl-legacy-provider
You can read about this flag before setting it.

**Comment by DVGY** [comment]
For some reason this is not working for me.

**Comment by alonshmiel** [comment]
Please try the suggested solutions here:
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by DVGY** [comment]
I tried this. It seems I need to downgrade my version to 16, other methods are not working. 
@alonshmiel if this project can use `Volta` I think then it will be great. Let me know if you think it a good thing to integrate volta, if yes I can create a PR

**Comment by alonshmiel** [comment]
Do you start your project with npm? react-script?

**Comment by DVGY** [comment]
> Do you start your project with npm? react-script?

I am using npm start command

Failed to compile.

./src/test/theming-test.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/test/theming-test.scss)
Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (108)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1

```
 "start": "react-scripts  --openssl-legacy-provider start",
```

**Comment by alonshmiel** [comment]
Please try:
npm uninstall node-sass
npm install sass

**Comment by DVGY** [comment]
Working now Great !!

**Comment by DVGY** [comment]
Closing this for now
