### ISSUE TITLE
Error when returning false in onSelectionChanging

### ISSUE THREAD

**Issue by mathdevelop** [silevis/reactgrid#247]
If I do not want to select a cell and return false in the onSelectionChanging callback, the following error occurs:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'last')
    at eval (handleStateUpdate-13a9c5a8.js:1:206532)
    at eval (handleStateUpdate-13a9c5a8.js:1:206920)
    at Ga (handleStateUpdate-13a9c5a8.js:1:214417)
    at t.handleKeyDown (handleStateUpdate-13a9c5a8.js:1:231363)
    at eval (handleStateUpdate-13a9c5a8.js:1:28738)
    at e.stateUpdater [as updateState] (handleStateUpdate-13a9c5a8.js:1:198367)
    at Le.keyDownHandler (handleStateUpdate-13a9c5a8.js:1:28704)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js:9097:1)
    at eval (react-dom.development.js:9288:1)
    at batchedUpdates$1 (react-dom.development.js:26140:1)
    at batchedUpdates (react-dom.development.js:3991:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:1)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:1)
    at dispatchEvent (react-dom.development.js:6457:1)
    at dispatchDiscreteEvent (react-dom.development.js:6430:1)
```

Code:
```
const handleSelectionChanged = (selectedRanges: any) => {
  // console.log('handleSelectionChanged')
  // console.log(selectedRanges)
}

const handleSelectionChanging = (selectedRanges: any): boolean => {
  // There may be some condition or not
  return false
}

<ReactGrid
  ...
  onSelectionChanged={handleSelectionChanging}
  onSelectionChanging={handleSelectionChanging}
  enableRangeSelection
/>
```

**Comment by DLowHP** [comment]
Hi! I couldn't reproduce this, could you provide a sandbox?

**Comment by DLowHP** [comment]
Nevermind, it seems it fails when selecting with shift + arrow, but not with the mouse...

**Comment by DLowHP** [comment]
Should work with the linked change
