### ISSUE TITLE
Document using the grid with NextJS, or fix the import issue

### ISSUE THREAD

**Issue by craigglennie** [silevis/reactgrid#36]
**Describe the bug**
When using NextJS and the ReactGrid ReadMe example the following error occurs

```
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:992:16)
    at Module._compile (internal/modules/cjs/loader.js:1040:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at eval (webpack-internal:///@silevis/reactgrid:1:18)
    at Object.@silevis/reactgrid (/Users/[redacted]/.next/server/pages/index.js:126:1)
    at __webpack_require__ (/Users/[redacted]/.next/server/pages/index.js:23:31)
```

Reporting this as a bug because I don't know enough about the module systems / NextJS to know if this should be fixed in reactgrid, or if the workaround I've included is actually the right thing to do (if so, I'd propose adding it to the ReadMe for this project, as NextJS is very popular)

**Current behavior**
The application fails to compile

**Expected behavior**
The grid component should work. This can be achieved by using `next-transpile-modules` [as documented](https://www.npmjs.com/package/next-transpile-modules#usage)

In `next.config.js`

```
const withTM = require('next-transpile-modules')(['@silevis/reactgrid']); 
module.exports = withTM()
```

**Comment by patryk0493** [comment]
Thank you, we added some info about integrations with Next.js.
