### ISSUE TITLE
Rendered more hooks than during the previous render.

### ISSUE THREAD

**Issue by JakeThurman** [silevis/reactgrid#64]
**Describe the bug**
I got an exception on https://reactgrid.com/examples/?example=multi-user

See error details below but the issue is "Rendered more hooks than during the previous render.". (You may never use hooks inside an if statement.).

I am able to repro the issue from the example consitently by Dragging the "is active" column into the sticky'd area.

**Screenshots or gifs**
![brave_I1OlCg8rXN](https://user-images.githubusercontent.com/11357914/148844978-84c4d887-306c-43a8-9a31-80d833b393ee.gif)

**Error Content**
```
Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. at ro (https://reactgrid.com/framework-5631da51a100b78da9c4.js:2:71062) at ao (https://reactgrid.com/framework-5631da51a100b78da9c4.js:2:71313) at Object.useState (https://reactgrid.com/framework-5631da51a100b78da9c4.js:2:77635) at Object.t.useState (https://reactgrid.com/framework-5631da51a100b78da9c4.js:2:11559) at e.t.render (https://reactgrid.com/191d5c1a0194a95d452020f30c3ec9bdcb7e560a-9b50cfe10ba32f2fe7b8.js:2:31473) at el (https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:176234) at to (https://reactgrid.com/framework-5631da51a100b78da9c4.js:2:70511) at Ao (https://reactgrid.com/framework-5631da51a100b78da9c4.js:2:80029) at Bu (https://reactgrid.com/framework-5631da51a100b78da9c4.js:2:123921) at Ei (https://reactgrid.com/framework-5631da51a100b78da9c4.js:2:109959) at el (https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:173812) at ta (https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:446460) at https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:177223 at https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:177978 at al (https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:178933) at div at cl (https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:179642) at ll (https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:178772) at oa (https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:446749) at div at div at t (https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:171265) at Ui (https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:171915) at t (https://reactgrid.com/8abd31c1-62d1db579c1613a0b298.js:1:456310) at div at C (https://reactgrid.com/191d5c1a0194a95d452020f30c3ec9bdcb7e560a-9b50cfe10ba32f2fe7b8.js:2:279224) at be (https://reactgrid.com/191d5c1a0194a95d452020f30c3ec9bdcb7e560a-9b50cfe10ba32f2fe7b8.js:2:49278) at div at div at p (https://reactgrid.com/f926e40590dbf8052a96fd5dcd43a02a65b8b6f6-f10ebc367c57d9ce0f0a.js:2:118292) at div at u (https://reactgrid.com/f926e40590dbf8052a96fd5dcd43a02a65b8b6f6-f10ebc367c57d9ce0f0a.js:2:103024) at div at k (https://reactgrid.com/component---src-pages-examples-tsx-6b3c45189a6680440a3c.js:1:1009) at D (https://reactgrid.com/component---src-pages-examples-tsx-6b3c45189a6680440a3c.js:1:18061) at div at t (https://reactgrid.com/component---src-pages-examples-tsx-6b3c45189a6680440a3c.js:1:442) at ul at u (https://reactgrid.com/f926e40590dbf8052a96fd5dcd43a02a65b8b6f6-f10ebc367c57d9ce0f0a.js:2:44725) at div at p (https://reactgrid.com/f926e40590dbf8052a96fd5dcd43a02a65b8b6f6-f10ebc367c57d9ce0f0a.js:2:118292) at div at u (https://reactgrid.com/f926e40590dbf8052a96fd5dcd43a02a65b8b6f6-f10ebc367c57d9ce0f0a.js:2:103024) at div at u (https://reactgrid.com/f926e40590dbf8052a96fd5dcd43a02a65b8b6f6-f10ebc367c57d9ce0f0a.js:2:480) at $ (https://reactgrid.com/component---src-pages-examples-tsx-6b3c45189a6680440a3c.js:1:18966) at main at t.a (https://reactgrid.com/f926e40590dbf8052a96fd5dcd43a02a65b8b6f6-f10ebc367c57d9ce0f0a.js:2:40859) at RNt/.t.default (https://reactgrid.com/component---src-pages-examples-tsx-6b3c45189a6680440a3c.js:1:19994) at e (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:29336) at t at div at e (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:65405) at S (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:65152) at e (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:64191) at b (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:62357) at j at e (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:25892) at e (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:50672) at o (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:54340) at d (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:13973) at c (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:23748) at https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:86860 at https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:13786 at e (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:51953) at e (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:62501) at b (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:62357) at n (https://reactgrid.com/app-9ca9e758c0c1fee9a121.js:2:53841) at n

```

**Your environment details**
 - Device:  Desktop
 - OS: Windows
 - Browser: Chorme

**Comment by czerwiukk** [comment]
Thank you for reporting the issue!
The problem has been resolved.
